version: '3.1'

services:
  bolsa_db:
    image: postgres:15-alpine
    container_name: empleabilidad_backend
    env_file:
      - .env
    ports:
      - '5435:5432'
    networks:
      - empleabilidad
volumes:
  postgres_data:

networks:
  empleabilidad: