services:

  db:
    image: postgres:12.5-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./dump_base.sql:/docker-entrypoint-initdb.d/dump_base.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: ["start-dev","--import-realm"]
    restart: unless-stopped
    volumes:
      - ./.keycloak/dev-realm.json:/opt/keycloak/data/import/dev-realm.json
    ports:
      - '8080:8080'
      - '8443:8443'
    env_file:
      - .env
    networks:
      default:
        aliases:
          - keycloak.localdev.me

volumes:
  pg_data: {}