version: '3.1'

services:
  bolsa_db:
    image: postgres:15-alpine
    container_name: empleabilidad_backend
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgres/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - empleabilidad
volumes:
  postgres_data:

networks:
  empleabilidad: